# Generated by Django 2.2.6 on 2019-10-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='team_leader',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
