# Generated by Django 2.2.6 on 2020-01-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image',
        ),
    ]
