# Generated by Django 2.2.6 on 2020-01-04 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_attachment_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
