# Generated by Django 2.2.6 on 2020-01-05 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200105_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='MSlug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Body', models.TextField(null=True)),
                ('Active', models.BooleanField(default=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Meeting_Comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post')),
                ('Parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.Comment')),
            ],
            options={
                'ordering': ('-Created',),
            },
        ),
    ]
