# Generated by Django 2.2.6 on 2020-01-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200105_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='department',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.RemoveField(
            model_name='post',
            name='team_leader',
        ),
        migrations.AlterField(
            model_name='post',
            name='type_of_food',
            field=models.IntegerField(blank=True, choices=[(1, 'VEG'), (2, 'NONVEG'), (3, 'VEG/NONVEG')], null=True),
        ),
    ]
