# Generated by Django 2.2.6 on 2020-01-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200105_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Body1',
            field=models.TextField(null=True),
        ),
    ]
