# Generated by Django 2.2.6 on 2020-01-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_comment_body1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Body1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
