# Generated by Django 2.2.6 on 2020-01-06 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200106_0133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Body1',
            new_name='Bodysss',
        ),
    ]
