# Generated by Django 2.2.6 on 2020-01-06 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200106_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Bodysss',
            new_name='Bod',
        ),
    ]
