# Generated by Django 2.2.6 on 2020-01-07 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200106_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Name',
            new_name='UserName',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Bod',
        ),
    ]
