# Generated by Django 2.2.6 on 2020-01-07 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_volunteer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-Createds',)},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Active',
            new_name='Actives',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Created',
            new_name='Createds',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Parent',
            new_name='Parents',
        ),
    ]
