# Generated by Django 2.2.6 on 2020-01-07 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200107_0351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-Created',)},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Actives',
            new_name='Active',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Createds',
            new_name='Created',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Parents',
            new_name='Parent',
        ),
    ]
