# Generated by Django 2.2.6 on 2020-01-07 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20200107_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='comment',
            name='Event_Comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments1', to='blog.Post'),
        ),
    ]
