# Generated by Django 2.2.6 on 2020-01-07 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20200107_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Event_Comment',
        ),
    ]
