# Generated by Django 2.2.6 on 2020-01-08 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_remove_comment_event_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='blog.Post'),
        ),
    ]
