# Generated by Django 2.2.6 on 2020-01-08 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_comment_meeting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='if_any_details',
            new_name='if_any_details_or_variety',
        ),
    ]
