# Generated by Django 2.2.6 on 2020-01-08 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20200108_0450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='if_any_details_or_variety',
            new_name='if_any_details_or_variety_of_food',
        ),
    ]
