# Generated by Django 2.2.6 on 2020-01-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_comment_required_quntity'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='expire_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
