# Generated by Django 3.0.2 on 2020-01-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_post_expire_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='longi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
