# Generated by Django 3.0.2 on 2020-01-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20200127_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type_of_food',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Veg/Nonveg', 'Veg/Nonveg')], default='Veg', max_length=20),
        ),
    ]
