# Generated by Django 3.0.2 on 2020-01-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20200127_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type_of_food',
            field=models.CharField(blank=True, choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Veg/Nonveg', 'Veg/Nonveg')], default='Veg', max_length=20, null=True),
        ),
    ]
