# Generated by Django 3.0.2 on 2020-01-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20200127_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_act',
            field=models.BooleanField(default=True),
        ),
    ]
