# Generated by Django 3.0.2 on 2020-01-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20200127_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_of_food1',
        ),
        migrations.AddField(
            model_name='post',
            name='details',
            field=models.FileField(blank=True, null=True, upload_to='musics/'),
        ),
    ]
