# Generated by Django 3.0.2 on 2020-01-28 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_auto_20200127_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='lat',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='longi',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='venue',
            new_name='longitude',
        ),
        migrations.RemoveField(
            model_name='post',
            name='city',
        ),
        migrations.RemoveField(
            model_name='post',
            name='if_any_details_or_variety_of_food',
        ),
        migrations.RemoveField(
            model_name='post',
            name='if_possible_say_main_ingredients',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pick_up_time',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pincode',
        ),
    ]
