# Generated by Django 3.0.2 on 2020-01-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_auto_20200128_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='detail',
            field=models.FileField(blank=True, null=True, upload_to='musics/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
