# Generated by Django 3.0.2 on 2020-01-28 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_auto_20200128_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='details',
            new_name='details_audio',
        ),
    ]
