# Generated by Django 2.2.6 on 2020-02-27 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='content',
            new_name='Content',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='department',
            new_name='Name',
        ),
    ]
