# Generated by Django 2.2.6 on 2020-03-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='slider'),
        ),
    ]
