# Generated by Django 2.2.6 on 2020-01-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type_of_user',
            field=models.IntegerField(blank=True, choices=[(1, 'Cooking'), (2, 'Ready'), (3, 'On the way'), (4, 'Delivered')], null=True),
        ),
    ]
