# Generated by Django 2.2.6 on 2020-01-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_profile_type_of_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type_of_user',
            field=models.IntegerField(blank=True, choices=[(1, 'Donor'), (2, 'Hungers(Acceptors)'), (3, 'Volunteer')], null=True),
        ),
    ]
