# Generated by Django 2.2.6 on 2020-01-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_profile_nature_of_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='any_thing_would_you_like_to_tell_us',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='does_it_accept_raw_food',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='does_it_have_kitchen',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='please_specify_food_perference',
            field=models.IntegerField(blank=True, choices=[(1, 'CATRER'), (2, 'COMPANY'), (3, 'COLLEGE')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='status_of_registration',
            field=models.IntegerField(blank=True, choices=[(1, 'Govt support entity(Registered)'), (2, 'Non Govt support entity(Registered)'), (3, 'Individual led charitable(Unregistered)'), (4, 'Unorganized Space(Unregistered)'), (5, 'Others')], null=True),
        ),
    ]
