# Generated by Django 2.2.6 on 2020-01-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20200105_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='how_would_you_like_to_help',
            field=models.IntegerField(blank=True, choices=[(1, 'Volunteer'), (2, 'Work On Technology Platform')], null=True),
        ),
    ]
