# Generated by Django 2.2.6 on 2020-01-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_profile_how_would_you_like_to_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='longi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
