# Generated by Django 2.2.6 on 2020-01-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20200105_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='longi',
            new_name='longitude',
        ),
    ]
