# Generated by Django 3.0.2 on 2020-01-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20200127_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='how_would_you_like_to_help',
            field=models.CharField(blank=True, choices=[('Volunteer', 'Volunteer'), ('Work On Technology Platform', 'Work On Technology Platform')], default='Volunteer', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nature_of_institution',
            field=models.CharField(blank=True, choices=[('CATRER', 'CATRER'), ('COMPANY', 'COMPANY'), ('COLLEGE', 'COLLEGE'), ('SCHOOL', 'SCHOOL'), ('FACTORY', 'FACTORY'), ('HOSTEL', 'HOSTEL')], default='CATRER', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status_of_registration',
            field=models.CharField(blank=True, choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Veg/Nonveg', 'Veg/Nonveg')], default='Govt support entity(Registered)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type_of_user',
            field=models.CharField(blank=True, choices=[('Donor', 'Donor'), ('Hungers(Acceptors)', 'Hungers(Acceptors)'), ('Volunteer', 'Volunteer')], default='Donor', max_length=20, null=True),
        ),
    ]
